# Generated by Django 3.1.2 on 2020-10-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=20)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
