# Generated by Django 3.1.2 on 2020-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201013_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingno', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
