# Generated by Django 3.1.2 on 2020-11-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Order has been successfully picked up', max_length=50),
        ),
    ]
