# Generated by Django 3.1.2 on 2020-11-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='packname',
            field=models.CharField(default='Unknow', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(default='S', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='types',
            field=models.CharField(default='Unknow', max_length=50),
        ),
    ]
