# Generated by Django 3.1.2 on 2020-11-10 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20201110_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
