# Generated by Django 3.1.2 on 2020-11-10 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_post_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdate',
            field=models.DateTimeField(default=datetime.datetime, editable=False),
        ),
    ]
