# Generated by Django 3.1.2 on 2020-11-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20201110_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sensorid',
            field=models.CharField(default='001', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='line',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='picked up', max_length=50),
        ),
    ]
