# Generated by Django 3.1.2 on 2020-11-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20201115_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
