# Generated by Django 3.1.2 on 2020-11-24 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0015_auto_20201115_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sensorid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='types',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=50, null=True)),
                ('storephone', models.CharField(max_length=50, null=True)),
                ('storeaddress', models.TextField(max_length=200, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
