# Generated by Django 3.1.2 on 2020-12-01 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0019_auto_20201129_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='username',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
