# Generated by Django 3.1.2 on 2020-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_profiles_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='storeaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
