# Generated by Django 3.1.2 on 2020-12-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20201201_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='esp8266',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibration', models.IntegerField(max_length=50)),
                ('latitude', models.BooleanField()),
                ('longtitude', models.BooleanField()),
                ('day', models.CharField(max_length=50)),
            ],
        ),
    ]
