# Generated by Django 3.1.2 on 2020-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_esp8266'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp8266',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='esp8266',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='esp8266',
            name='day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='esp8266',
            name='latitude',
            field=models.FloatField(null=True),
        ),
    ]
