# Generated by Django 3.1.2 on 2020-12-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_auto_20201210_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.profiles'),
        ),
        migrations.AlterField(
            model_name='esp8266',
            name='vibration',
            field=models.IntegerField(),
        ),
    ]
