# Generated by Django 3.1.2 on 2020-12-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_auto_20201219_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
